name: CI

on:
  push:
    branches: [main, std20_dev]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: write
    uses: koomx/x-ci/.github/workflows/vcpkg-template.yml@main
    with:
      enable-std20-ubuntu24-amd64: true
      enable-std20-ubuntu24-arm64: true
      config-command: |
        cmake --preset=ci -DCMAKE_BUILD_TYPE=Release
      build-command: |
        cmake --build build-ninja -j$(nproc)
      test-command: |
        ctest --test-dir build-ninja --output-on-failure -j1
      benchmark-command: |
        python3 scripts/run_log_bench.py
      plot-command: |
        python3 scripts/plot_log_bench.py
      benchmark-publish-branch: benchmark-results
      benchmark-publish-job: ''
